# -*- coding: utf-8 -*-
"""K-Means Klastering CSV.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g-1OjQh3iK5eUi7m2DR5zURErv2Vd26m
"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.cluster import KMeans

datasets = pd.read_csv('konsumen.csv')
datasets.keys()

dataku = pd.DataFrame(datasets)
dataku.head()

X = np.asarray(datasets)
print(X)

plt.scatter(X[:,0], X[:,1], label='True Position')
plt.xlabel("X")
plt.ylabel("Y")
plt.title("Grafik Hasil ")
plt.show()

kmeans = KMeans(n_clusters=2)
kmeans.fit(X)

print(kmeans.cluster_centers_)

plt.scatter(X[:,0], X[:,1], c=kmeans.labels_, cmap='rainbow')
plt.xlabel("X")
plt.ylabel("Y")
plt.title("Grafik Hasil")
plt.show()

plt.scatter(X[:,0], X[:,1], c=kmeans.labels_, cmap='rainbow')
plt.scatter(kmeans.cluster_centers_[:,0], kmeans.cluster_centers_[:,1], color='black')
plt.xlabel("X")
plt.ylabel("Y")
plt.title("Grafik Hasil")
plt.show()